  version: "3"
  tasks:
      generate:
            aliases:
                  - gen
            desc: "codegen from proto"
            cmds:
                  - protoc -I proto proto/exchange/exchange.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
      mobgenerate:
            aliases:
                  - mobgen
            desc: "codegen from proto"
            cmds:
                  - protoc -I proto proto/mobexchange/mobexchange.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
